export default [
  {
    "name": "demo.vue",
    "scriptContent": "\nimport { ref } from 'vue'\nimport { toRefs } from '@vueuse/shared'\nimport Scrubber from '../../core/useMediaControls/components/Scrubber.vue'\nimport { useDrauu } from '.'\n\nconst colors = ref(['black', '#ef4444', '#22c55e', '#3b82f6'])\nconst target = ref()\nconst { undo, redo, canUndo, canRedo, clear, brush } = useDrauu(target, {\n  brush: {\n    color: 'black',\n    size: 3,\n  },\n})\n\nconst { mode, color, size } = toRefs(brush)\n",
    "templateContent": "\n  <div flex=\"~ col\" place=\"items-center\">\n    <div\n      shadow=\"~ lg\"\n      class=\"drauu-demo\"\n      border=\"rounded\"\n      overflow=\"hidden\"\n      max-w=\"screen-lg\"\n      h=\"[60vh]\"\n      w=\"full\"\n      flex=\"~ col\"\n    >\n      <div\n        bg=\"$vt-c-bg\"\n        border=\"1 $vt-c-divider\"\n        rounded-t\n        flex=\"~ row\"\n        items=\"center\"\n        p=\"2\"\n        space=\"x-4\"\n      >\n        <div flex=\"~ row 1\">\n          <button\n            v-for=\"_color in colors\"\n            :key=\"_color\"\n            :class=\"{ active: _color === color }\"\n            class=\"color-button\"\n            m=\"r-1\"\n            @click=\"() => color = _color\"\n          >\n            <div :style=\"{ background: _color }\" w=\"6\" h=\"6\" border=\"2 dark:(light-900 opacity-50) rounded-full\" />\n          </button>\n        </div>\n        <div flex=\"~ row 1 shrink-1\" items=\"center\" w=\"full\" max-w=\"64\">\n          <carbon-paint-brush m=\"r-2\" />\n          <Scrubber v-model=\"size\" w=\"full\" :min=\"1\" :max=\"10\" />\n        </div>\n        <div flex=\"~ row 1\" justify=\"end\">\n          <button class=\"tool-button\" :disabled=\"!canUndo\" @click=\"undo()\">\n            <carbon-undo />\n          </button>\n          <button class=\"tool-button\" :disabled=\"!canRedo\" @click=\"redo()\">\n            <carbon-redo />\n          </button>\n          <button class=\"tool-button\" @click=\"clear()\">\n            <carbon-clean />\n          </button>\n        </div>\n      </div>\n      <div flex=\"~ row 1\" h=\"72\">\n        <div\n          bg=\"$vt-c-bg\"\n          border=\"t-0 1 $vt-c-divider\"\n          rounded-b\n          flex=\"~ col\"\n          space=\"y-2\"\n          place=\"items-center\"\n          p=\"2\"\n        >\n          <button :class=\"{ active: brush.mode === 'draw' }\" class=\"tool-button\" @click=\"mode = 'draw'\">\n            <carbon-pen />\n          </button>\n          <button :class=\"{ active: brush.mode === 'line' && !brush.arrowEnd }\" class=\"tool-button\" @click=\"mode = 'line'\">\n            <mdi-slash-forward />\n          </button>\n          <button :class=\"{ active: brush.mode === 'rectangle' }\" class=\"tool-button\" @click=\"mode = 'rectangle'\">\n            <carbon-checkbox />\n          </button>\n          <button :class=\"{ active: brush.mode === 'ellipse' }\" class=\"tool-button\" @click=\"mode = 'ellipse'\">\n            <mdi-light-shape-circle />\n          </button>\n        </div>\n        <svg\n          ref=\"target\"\n          w=\"full\"\n          h=\"full\"\n          bg=\"white\"\n        />\n      </div>\n    </div>\n  </div>\n",
    "styleContent": "\n.drauu-demo .tool-button {\n  @apply rounded-full m-0 bg-transparent text-dark-50 border-none h-8 w-8 p-0 flex place-items-center place-content-center;\n}\n\n.dark .drauu-demo .tool-button {\n  @apply text-light-900;\n}\n\n.drauu-demo .tool-button:disabled {\n  @apply text-light-900 bg-transparent border-none;\n}\n\n.dark .drauu-demo .tool-button:disabled {\n  @apply text-dark-50;\n}\n\n.drauu-demo .tool-button:hover {\n  @apply text-green-900;\n}\n\n.drauu-demo .tool-button.active {\n  @apply bg-green-500 text-green-900;\n}\n\n.drauu-demo .color-button {\n  @apply m-0 bg-transparent text-dark-50 rounded-full border-none h-8 w-8 p-0 flex place-items-center place-content-center;\n}\n\n.dark .drauu-demo .color-button {\n  @apply ;\n}\n\n.drauu-demo .color-button:hover,\n.drauu-demo .color-button.active {\n  @apply bg-light-900;\n}\n\n.dark .drauu-demo .color-button:hover,\n.dark .drauu-demo .color-button.active {\n  @apply bg-dark-300;\n}\n",
    "path": "packages/integrations/useDrauu/demo.vue"
  }
]
