export default [
  {
    "filename": "demo.vue",
    "script": "import { ref } from 'vue'\nimport { toRefs } from '@vueuse/shared'\nimport Scrubber from './Scrubber.vue'\nimport { useDrauu } from '.'\n\nconst colors = ref(['black', '#ef4444', '#22c55e', '#3b82f6'])\nconst target = ref()\nconst { undo, redo, canUndo, canRedo, clear, brush } = useDrauu(target, {\n  brush: {\n    color: 'black',\n    size: 3,\n  },\n})\n\nconst { mode, color, size } = toRefs(brush)",
    "template": "<div flex=\"~ col\" place=\"items-center\">\n    <div\n      shadow=\"~ lg\"\n      class=\"drauu-demo\"\n      border=\"rounded\"\n      overflow=\"hidden\"\n      max-w=\"screen-lg\"\n      h=\"[60vh]\"\n      w=\"full\"\n      flex=\"~ col\"\n    >\n      <div\n        bg=\"$vt-c-bg\"\n        border=\"1 $vt-c-divider\"\n        rounded-t\n        flex=\"~ row\"\n        items=\"center\"\n        p=\"2\"\n        space=\"x-4\"\n      >\n        <div flex=\"~ row 1\">\n          <button\n            v-for=\"_color in colors\"\n            :key=\"_color\"\n            :class=\"{ active: _color === color }\"\n            class=\"color-button\"\n            m=\"r-1\"\n            @click=\"() => color = _color\"\n          >\n            <div :style=\"{ background: _color }\" w=\"6\" h=\"6\" border=\"2 dark:(light-900 opacity-50) rounded-full\" />\n          </button>\n        </div>\n        <div flex=\"~ row 1 shrink-1\" items=\"center\" w=\"full\" max-w=\"64\">\n          <i i-carbon-paint-brush m=\"r-2\" />\n          <Scrubber v-model=\"size\" w=\"full\" :min=\"1\" :max=\"10\" />\n        </div>\n        <div flex=\"~ row 1\" justify=\"end\">\n          <button class=\"tool-button\" :disabled=\"!canUndo\" @click=\"undo()\">\n            <i i-carbon-undo />\n          </button>\n          <button class=\"tool-button\" :disabled=\"!canRedo\" @click=\"redo()\">\n            <i i-carbon-redo />\n          </button>\n          <button class=\"tool-button\" @click=\"clear()\">\n            <i i-carbon-clean />\n          </button>\n        </div>\n      </div>\n      <div flex=\"~ row 1\" h=\"72\">\n        <div\n          bg=\"$vt-c-bg\"\n          border=\"t-0 1 $vt-c-divider\"\n          rounded-b\n          flex=\"~ col\"\n          space=\"y-2\"\n          place=\"items-center\"\n          p=\"2\"\n        >\n          <button :class=\"{ active: brush.mode === 'draw' }\" class=\"tool-button\" @click=\"mode = 'draw'\">\n            <i i-carbon-pen />\n          </button>\n          <button :class=\"{ active: brush.mode === 'line' && !brush.arrowEnd }\" class=\"tool-button\" @click=\"mode = 'line'\">\n            <i i-mdi-slash-forward />\n          </button>\n          <button :class=\"{ active: brush.mode === 'rectangle' }\" class=\"tool-button\" @click=\"mode = 'rectangle'\">\n            <i i-carbon-checkbox />\n          </button>\n          <button :class=\"{ active: brush.mode === 'ellipse' }\" class=\"tool-button\" @click=\"mode = 'ellipse'\">\n            <i i-mdi-light-shape-circle />\n          </button>\n        </div>\n        <svg\n          ref=\"target\"\n          w=\"full\"\n          h=\"full\"\n          bg=\"white\"\n        />\n      </div>\n    </div>\n  </div>",
    "style": ".drauu-demo .tool-button {\n  @apply rounded-full m-0 bg-transparent text-dark-50 border-none h-8 w-8 p-0 flex place-items-center place-content-center;\n}\n\n.dark .drauu-demo .tool-button {\n  @apply text-light-900;\n}\n\n.drauu-demo .tool-button:disabled {\n  @apply text-light-900 bg-transparent border-none;\n}\n\n.dark .drauu-demo .tool-button:disabled {\n  @apply text-dark-50;\n}\n\n.drauu-demo .tool-button:hover {\n  @apply text-green-900;\n}\n\n.drauu-demo .tool-button.active {\n  @apply bg-green-500 text-green-900;\n}\n\n.drauu-demo .color-button {\n  @apply m-0 bg-transparent text-dark-50 rounded-full border-none h-8 w-8 p-0 flex place-items-center place-content-center;\n}\n\n.dark .drauu-demo .color-button {\n  @apply ;\n}\n\n.drauu-demo .color-button:hover,\n.drauu-demo .color-button.active {\n  @apply bg-light-900;\n}\n\n.dark .drauu-demo .color-button:hover,\n.dark .drauu-demo .color-button.active {\n  @apply bg-dark-300;\n}"
  },
  {
    "filename": "Scrubber.vue",
    "script": "import { ref, watch } from 'vue-demi'\nimport { useEventListener, useMouseInElement, useVModel } from '@vueuse/core'\n\nconst scrubber = ref()\nconst scrubbing = ref(false)\nconst pendingValue = ref(0)\n\nuseEventListener('mouseup', () => scrubbing.value = false)\n\nconst emit = defineEmits(['update:modelValue'])\nconst props = defineProps({\n  min: { type: Number, default: 0 },\n  max: { type: Number, default: 100 },\n  secondary: { type: Number, default: 0 },\n  modelValue: { type: Number, required: true },\n})\n\nconst value = useVModel(props, 'modelValue', emit)\nconst { elementX, elementWidth } = useMouseInElement(scrubber)\n\nwatch([scrubbing, elementX], () => {\n  const progress = Math.max(0, Math.min(1, (elementX.value) / elementWidth.value))\n  pendingValue.value = progress * props.max\n  if (scrubbing.value)\n    value.value = pendingValue.value\n})",
    "template": "<div ref=\"scrubber\" class=\"relative h-2 rounded cursor-pointer select-none bg-black dark:bg-white dark:bg-opacity-10 bg-opacity-20\" @mousedown=\"scrubbing = true\">\n    <div class=\"relative overflow-hidden h-full w-full rounded\">\n      <div class=\"h-full absolute opacity-30 left-0 top-0 bg-emerald-700 w-full rounded\" :style=\"{ 'transform': `translateX(${ secondary / max * 100 - 100 }%)` }\" />\n      <div class=\"relative h-full w-full bg-emerald-500 rounded\" :style=\"{ 'transform': `translateX(${ value / max * 100 - 100 }%)` }\" />\n    </div>\n    <div class=\"absolute inset-0 hover:opacity-100 opacity-0\" :class=\"{ '!opacity-100': scrubbing }\">\n      <slot :pendingValue=\"pendingValue\" :position=\"`${Math.max(0, Math.min(elementX, elementWidth))}px`\" />\n    </div>\n  </div>"
  }
]
