export default [
  {
    "name": "demo.vue",
    "scriptContent": "\nimport type { Ref } from 'vue'\nimport { ref } from 'vue'\nimport { useBase64 } from '@vueuse/core'\n\nconst text = ref('')\nconst file = ref() as Ref<File>\nconst image = ref() as Ref<HTMLImageElement>\n\nconst { base64: textBase64 } = useBase64(text)\nconst { base64: fileBase64 } = useBase64(file)\nconst { base64: imageBase64 } = useBase64(image)\nconst { base64: bufferBase64 } = useBase64(new ArrayBuffer(8))\n\nfunction onFileInput(e: Event) {\n  file.value = (e.target as HTMLInputElement).files![0]\n}\n",
    "templateContent": "\n  <div space-y-4>\n    <div grid md:grid-cols-2 gap-2>\n      <div>\n        <span>Text Input</span>\n        <textarea v-model=\"text\" h-40 type=\"text\" placeholder=\"Type something...\" />\n      </div>\n      <div>\n        <span>Base64</span>\n        <textarea h-40 :value=\"textBase64\" readonly />\n      </div>\n    </div>\n\n    <div grid md:grid-cols-2 gap-2>\n      <div>\n        <span>Buffer Input</span>\n        <pre mt-2>new ArrayBuffer(1024)</pre>\n      </div>\n      <div>\n        <span>Base64</span>\n        <textarea h-40 :value=\"bufferBase64\" readonly />\n      </div>\n    </div>\n\n    <div grid md:grid-cols-2 gap-2>\n      <div>\n        <span>File Input</span>\n        <div>\n          <input mt-2 type=\"file\" @input=\"onFileInput\">\n        </div>\n      </div>\n      <div>\n        <span>Base64</span>\n        <textarea h-40 :value=\"fileBase64\" readonly />\n      </div>\n    </div>\n\n    <div grid md:grid-cols-2 gap-2>\n      <div>\n        <span>Image Input</span>\n        <img\n          ref=\"image\"\n          w-full h-40 object-cover\n          class=\"rounded mt-2\"\n          src=\"https://images.unsplash.com/photo-1494256997604-768d1f608cac?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=200&q=80\"\n        >\n      </div>\n      <div>\n        <span>Base64</span>\n        <textarea h-40 :value=\"imageBase64\" readonly />\n      </div>\n    </div>\n  </div>\n",
    "styleContent": "\ntextarea {\n  min-width: 0px !important;\n  width: 100%;\n}\n",
    "path": "packages/core/useBase64/demo.vue"
  }
]
