export default [
  {
    "name": "demo.vue",
    "scriptContent": "\nimport { computed, ref } from 'vue'\nimport type { SwipeDirection } from '@vueuse/core'\nimport { useSwipe } from '@vueuse/core'\n\nconst target = ref<HTMLElement | null>(null)\nconst container = ref<HTMLElement | null>(null)\nconst containerWidth = computed(() => container.value?.offsetWidth)\nconst left = ref('0')\nconst opacity = ref(1)\n\nconst reset = () => {\n  left.value = '0'\n  opacity.value = 1\n}\n\nconst { direction, isSwiping, lengthX, lengthY } = useSwipe(\n  target, {\n    passive: false,\n    onSwipe(e: TouchEvent) {\n      if (containerWidth.value) {\n        if (lengthX.value < 0) {\n          const length = Math.abs(lengthX.value)\n          left.value = `${length}px`\n          opacity.value = 1.1 - length / containerWidth.value\n        }\n        else {\n          left.value = '0'\n          opacity.value = 1\n        }\n      }\n    },\n    onSwipeEnd(e: TouchEvent, direction: SwipeDirection) {\n      if (lengthX.value < 0 && containerWidth.value && (Math.abs(lengthX.value) / containerWidth.value) >= 0.5) {\n        left.value = '100%'\n        opacity.value = 0\n      }\n      else {\n        left.value = '0'\n        opacity.value = 1\n      }\n    },\n  })\n",
    "templateContent": "\n  <div>\n    <div ref=\"container\" class=\"container select-none\">\n      <button @click=\"reset\">\n        Reset\n      </button>\n      <div ref=\"target\" class=\"overlay\" :class=\"{animated: !isSwiping}\" :style=\"{left, opacity}\">\n        <p>Swipe right</p>\n      </div>\n    </div>\n    <p class=\"status\">\n      Direction: {{ direction? direction : '-' }} <br>\n      lengthX: {{ lengthX }} | lengthY: {{ lengthY }}\n    </p>\n  </div>\n",
    "styleContent": "\n.container {\n  position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  border: 2px dashed #ccc;\n  height: 100;\n  overflow: hidden;\n}\n\n.overlay {\n  top: 0;\n  left: 0;\n  width: 100%;\n  height: 100%;\n  position: absolute;\n  background: #3fb983;\n}\n\n.overlay.animated {\n  transition: all 0.2s ease-in-out;\n}\n\n.overlay > p {\n  color: #fff;\n  font-weight: bold;\n  text-align: center;\n  overflow:hidden;\n  white-space: nowrap;\n}\n\n.status {\n  text-align: center;\n}\n",
    "path": "packages/core/useSwipe/demo.vue"
  }
]
