export default [
  {
    "name": "demo.vue",
    "scriptContent": "\nimport { rand } from '@vueuse/shared'\nimport { ref } from 'vue'\nimport { TransitionPresets, useTransition } from '@vueuse/core'\n\nconst duration = 1500\n\nconst baseNumber = ref(0)\n\nconst baseVector = ref([0, 0])\n\nconst easeOutElastic = (n: number) => {\n  return n === 0\n    ? 0\n    : n === 1\n      ? 1\n      : (2 ** (-10 * n)) * Math.sin((n * 10 - 0.75) * ((2 * Math.PI) / 3)) + 1\n}\n\nconst cubicBezierNumber = useTransition(baseNumber, {\n  duration,\n  transition: [0.75, 0, 0.25, 1],\n})\n\nconst customFnNumber = useTransition(baseNumber, {\n  duration,\n  transition: easeOutElastic,\n})\n\nconst vector = useTransition(baseVector, {\n  duration,\n  transition: TransitionPresets.easeOutExpo,\n})\n\nconst toggle = () => {\n  baseNumber.value = baseNumber.value === 100 ? 0 : 100\n  baseVector.value = [rand(0, 100), rand(0, 100)]\n}\n",
    "templateContent": "\n  <div>\n    <button @click=\"toggle\">\n      Transition\n    </button>\n\n    <p class=\"mt-2\">\n      Cubic bezier curve: <b>{{ cubicBezierNumber.toFixed(2) }}</b>\n    </p>\n\n    <div class=\"track number\">\n      <div class=\"relative\">\n        <div class=\"sled\" :style=\"{ left: cubicBezierNumber + '%' }\" />\n      </div>\n    </div>\n\n    <p class=\"mt-2\">\n      Custom function: <b>{{ customFnNumber.toFixed(2) }}</b>\n    </p>\n\n    <div class=\"track number\">\n      <div class=\"relative\">\n        <div class=\"sled\" :style=\"{ left: customFnNumber + '%' }\" />\n      </div>\n    </div>\n\n    <p class=\"mt-2\">\n      Vector: <b>[{{ vector[0].toFixed(2) }}, {{ vector[1].toFixed(2) }}]</b>\n    </p>\n\n    <div class=\"track vector\">\n      <div class=\"relative\">\n        <div class=\"sled\" :style=\"{ left: vector[0] + '%', top: vector[1] + '%' }\" />\n      </div>\n    </div>\n  </div>\n",
    "styleContent": "\n.track {\n  background: rgba(125, 125, 125, 0.3);\n  border-radius: 0.5rem;\n  max-width: 20rem;\n  width: 100%;\n}\n\n.sled {\n  background: var(--vt-c-brand);\n  border-radius: 50%;\n  height: 1rem;\n  position: absolute;\n  width: 1rem;\n}\n\n.number.track {\n  height: 1rem;\n  margin: 0.5rem 0;\n  padding: 0 0.5rem;\n}\n\n.number.track .sled {\n  transform: translateX(-50%);\n}\n\n.vector.track {\n  padding: 0.5rem;\n}\n\n.vector.track .relative {\n  padding-bottom: 30%;\n}\n\n.vector.track .sled {\n  transform: translateX(-50%) translateY(-50%);\n}\n",
    "path": "packages/core/useTransition/demo.vue"
  }
]
