// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    Editor: typeof import('./modules/editor/Editor.vue')['default']
    EditorGroup: typeof import('./components/groups/EditorGroup.vue')['default']
    EditorTab: typeof import('./components/editor/EditorTab.vue')['default']
    EditorTabs: typeof import('./components/editor/EditorTabs.vue')['default']
    IconButton: typeof import('./components/ui/IconButton.vue')['default']
    Listbox: typeof import('./components/ui/listbox/Listbox.vue')['default']
    ListboxOption: typeof import('./components/ui/listbox/ListboxOption.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Menu: typeof import('./components/ui/menu/Menu.vue')['default']
    MenuItem: typeof import('./components/ui/menu/MenuItem.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Preview: typeof import('./modules/preview/Preview.vue')['default']
    ProjectSettings: typeof import('./modules/project/ProjectSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./modules/project/Settings.vue')['default']
    Spinner: typeof import('./components/ui/Spinner.vue')['default']
    Statusbar: typeof import('./modules/statusbar/Statusbar.vue')['default']
    StatusbarButton: typeof import('./modules/statusbar/StatusbarButton.vue')['default']
    StatusbarItemSelect: typeof import('./modules/statusbar/StatusbarItemSelect.vue')['default']
    StatusbarItemText: typeof import('./modules/statusbar/StatusbarItemText.vue')['default']
    Terminal: typeof import('./modules/terminal/Terminal.vue')['default']
    Titlebar: typeof import('./components/ui/Titlebar.vue')['default']
  }
}

export { }
