// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSetting: typeof import('./modules/app/components/AppSetting.vue')['default']
    Button: typeof import('./components/button/Button.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    DemoSelector: typeof import('./modules/project/components/DemoSelector.vue')['default']
    Dialog: typeof import('./components/dialog/Dialog.vue')['default']
    Editor: typeof import('./modules/editor/components/Editor.vue')['default']
    EditorAddTab: typeof import('./modules/editor/components/EditorAddTab.vue')['default']
    EditorGroup: typeof import('./modules/editor/components/EditorGroup.vue')['default']
    EditorTab: typeof import('./modules/editor/components/EditorTab.vue')['default']
    EditorTabs: typeof import('./modules/editor/components/EditorTabs.vue')['default']
    FocusContainer: typeof import('./components/FocusContainer.vue')['default']
    FunctionBadge: typeof import('./components/FunctionBadge.vue')['default']
    Hako: typeof import('./components/Hako.vue')['default']
    IconButton: typeof import('./components/button/IconButton.vue')['default']
    Item: typeof import('./components/Item.vue')['default']
    Listbox: typeof import('./components/listbox/Listbox.vue')['default']
    ListboxOption: typeof import('./components/listbox/ListboxOption.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    LogoHorizontal: typeof import('./components/LogoHorizontal.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    Message: typeof import('./modules/messages/components/Message.vue')['default']
    MessageTray: typeof import('./modules/messages/components/MessageTray.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NewProject: typeof import('./modules/project/components/NewProject.vue')['default']
    OpenDemo: typeof import('./modules/project/components/OpenDemo.vue')['default']
    PackageManager: typeof import('./modules/project/components/PackageManager.vue')['default']
    Preview: typeof import('./modules/preview/components/Preview.vue')['default']
    PreviewControls: typeof import('./modules/preview/components/PreviewControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select.vue')['default']
    Settings: typeof import('./modules/app/components/Settings.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    Statusbar: typeof import('./modules/statusbar/components/Statusbar.vue')['default']
    StatusbarButton: typeof import('./modules/statusbar/components/StatusbarButton.vue')['default']
    StatusbarItemSelect: typeof import('./modules/statusbar/components/StatusbarItemSelect.vue')['default']
    StatusbarItemText: typeof import('./modules/statusbar/components/StatusbarItemText.vue')['default']
    Templates: typeof import('./modules/app/components/Templates.vue')['default']
    Terminal: typeof import('./modules/terminal/Terminal.vue')['default']
    Textfield: typeof import('./components/Textfield.vue')['default']
    Titlebar: typeof import('./components/titlebar/Titlebar.vue')['default']
    TitlebarTab: typeof import('./components/titlebar/TitlebarTab.vue')['default']
    TitlebarTabs: typeof import('./components/TitlebarTabs.vue')['default']
    Welcome: typeof import('./modules/app/components/Welcome.vue')['default']
  }
}

export {}
