// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSetting: typeof import('./modules/app/components/AppSetting.vue')['default']
    Button: typeof import('./components/button/Button.vue')['default']
    Dialog: typeof import('./components/dialog/Dialog.vue')['default']
    Editor: typeof import('./modules/editor/components/Editor.vue')['default']
    EditorAddTab: typeof import('./modules/editor/components/EditorAddTab.vue')['default']
    EditorGroup: typeof import('./modules/editor/components/EditorGroup.vue')['default']
    EditorTab: typeof import('./modules/editor/components/EditorTab.vue')['default']
    EditorTabs: typeof import('./modules/editor/components/EditorTabs.vue')['default']
    Hako: typeof import('./components/Hako.vue')['default']
    IconButton: typeof import('./components/button/IconButton.vue')['default']
    Listbox: typeof import('./components/listbox/Listbox.vue')['default']
    ListboxOption: typeof import('./components/listbox/ListboxOption.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    Preview: typeof import('./modules/preview/components/Preview.vue')['default']
    PreviewControls: typeof import('./modules/preview/components/PreviewControls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./modules/app/components/Settings.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    Statusbar: typeof import('./modules/statusbar/components/Statusbar.vue')['default']
    StatusbarButton: typeof import('./modules/statusbar/components/StatusbarButton.vue')['default']
    StatusbarItemSelect: typeof import('./modules/statusbar/components/StatusbarItemSelect.vue')['default']
    StatusbarItemText: typeof import('./modules/statusbar/components/StatusbarItemText.vue')['default']
    Terminal: typeof import('./modules/terminal/Terminal.vue')['default']
    Titlebar: typeof import('./components/titlebar/Titlebar.vue')['default']
    TitlebarTab: typeof import('./components/titlebar/TitlebarTab.vue')['default']
    TitlebarTabs: typeof import('./components/titlebar/TitlebarTabs.vue')['default']
  }
}

export {}
